@TodoApi_HostAddress = http://localhost:5223

GET {{TodoApi_HostAddress}}/api/HavaDurumu/
Accept: application/json

###

GET {{TodoApi_HostAddress}}/api/TodoItems/
Accept: application/json

###

GET {{TodoApi_HostAddress}}/api/TodoItems/1
Accept: application/json

###